### ISSUE TITLE
setClientConfiguration fails for README example

### ISSUE THREAD

**Issue by brad811** [cleandart/react-dart#184]
The `setClientConfiguration` call is failing for me, so now I'm trying the example from the README and still getting the error: `Uncaught Error: Exception: react.js and react_dom.js must be loaded.`

I have the html file and dart file copy-pasted from the README.
Here is my `pubspec.yaml`:
```yaml
name: my_app
description: My app
environment:
  sdk: ^2.0.0
dev_dependencies:
  build_runner: ^1.3.0
  build_web_compilers: ^2.0.0
dependencies:
  react: ^4.5.0
```

I've run `pub get`.
I'm serving my app with `webdev serve`.
Dart version: `Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "macos_x64"`
